const EXPERIENSA_ROOT = process.cwd();
const EXPERIENSA_ASSETS = EXPERIENSA_ROOT + '/assets';
const EXPERIENSA_DIST = EXPERIENSA_ROOT + '/dist';
const NODEMOUDLES_PATH = EXPERIENSA_ROOT + '/node_modules';

module.exports = {
    EXPERIENSA_ROOT: EXPERIENSA_ROOT,
    EXPERIENSA_ASSETS: EXPERIENSA_ASSETS,
    EXPERIENSA_DIST: EXPERIENSA_DIST,
    NODEMOUDLES_PATH: NODEMOUDLES_PATH
};